/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package periodicoonline2;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan A. García Muelas <juangmuelas@hotmail.com>
 */
public class Usuarios extends javax.swing.JFrame {
    
     ArrayList<Usuario1>usuarios=new ArrayList();

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupPremium = new javax.swing.ButtonGroup();
        textUsuario = new javax.swing.JTextField();
        textContraseña = new javax.swing.JTextField();
        textDescuento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonAñadir = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botoningresos = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jPanelPremiun = new javax.swing.JPanel();
        opcionSiPremium = new javax.swing.JRadioButton();
        opcionNoPremium = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        jLabel3.setText("Descuento:");

        botonAñadir.setText("Añadir");
        botonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirActionPerformed(evt);
            }
        });

        botonLimpiar.setText("Limpiar");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botoningresos.setText("Ingresos");
        botoningresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoningresosActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jPanelPremiun.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente Premium"));

        buttonGroupPremium.add(opcionSiPremium);
        opcionSiPremium.setText("Si");

        buttonGroupPremium.add(opcionNoPremium);
        opcionNoPremium.setSelected(true);
        opcionNoPremium.setText("NO");

        javax.swing.GroupLayout jPanelPremiunLayout = new javax.swing.GroupLayout(jPanelPremiun);
        jPanelPremiun.setLayout(jPanelPremiunLayout);
        jPanelPremiunLayout.setHorizontalGroup(
            jPanelPremiunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPremiunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPremiunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcionSiPremium)
                    .addComponent(opcionNoPremium))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanelPremiunLayout.setVerticalGroup(
            jPanelPremiunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPremiunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(opcionSiPremium)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opcionNoPremium)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textContraseña)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(botonAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelPremiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botoningresos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(botonAñadir))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(botonLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(botonBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPremiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botoningresos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonSalir)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirActionPerformed
        
        // Creamos objeto user para guardar los datos
        Usuario1 User =new Usuario1();
        
        //Controlamos si el email es correcto 
        boolean correcto=true;
        
        Pattern ident = Pattern.compile("^([\\w-]+\\.)*?[\\w-]+@[\\w-]+\\.([\\w-]+\\.)*?[\\w]+$");
        Matcher id=ident.matcher(textUsuario.getText());
        if(id.matches())
             User.setEmail(textUsuario.getText());
         else{
             JOptionPane.showMessageDialog(this,"Formato de usuario incorrecto, debe ser un email válido." , "Error", JOptionPane.ERROR_MESSAGE);
             correcto=false;
             }
             User.setContraseña(textContraseña.getText());
             try{
                User.setDescuento(Double.parseDouble(textDescuento.getText()));
                }catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this,"Error al introducir el importe del descuento" , "Error", JOptionPane.ERROR_MESSAGE);
                correcto=false;
                }
                if (opcionSiPremium.isSelected()){
                    User.setPremium(true);
                }else
                    User.setPremium(false);
                if (correcto){
                    JOptionPane.showMessageDialog(this,"Usuario añadido correctamente." , "Añadido", JOptionPane.INFORMATION_MESSAGE);
                    usuarios.add(User);
                }else{
                    JOptionPane.showMessageDialog(this,"No se añadió el usuario." , "Error", JOptionPane.ERROR_MESSAGE);
                    }
            
    }//GEN-LAST:event_botonAñadirActionPerformed


    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        // TODO add your handling code here:
        textUsuario.setText("");
        textContraseña.setText("");
        textDescuento.setText("");
        buttonGroupPremium.clearSelection();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed

        // La búsqueda se hace por email
        
        Usuario1 user= new Usuario1();
        boolean encontrado=false;
        String email;
        email=textContraseña.getText();
        
        //Comprobar que la lista no está vacía con isEmpty
        if(!usuarios.isEmpty()){
            for(int i=0; i<usuarios.size()&&!encontrado;i++){
               // profe=profesores.get(i);
                if(email.equalsIgnoreCase(user.getEmail())){
                    encontrado=true;
                }
            }
        if(encontrado){
            textContraseña.setText(user.getContraseña());
            textUsuario.setText(user.getEmail());
            textDescuento.setText(user.getDescuento()+"");
            if(user.isPremium()){
                opcionSiPremium.setSelected(true);
            }else{
                opcionNoPremium.setSelected(true);
            }
            }else{
                JOptionPane.showMessageDialog(this, "NO existen coincidencias.", "No encontrado", JOptionPane.INFORMATION_MESSAGE);    
            }
            }else{
            JOptionPane.showMessageDialog(this,"No hay Usuarios dados de alta." , "Lista vacía", JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botoningresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoningresosActionPerformed
        // TODO add your handling code here:
         Double tarifa=0.0;
         Double prem=35.5; //tarifa premium
         Double noprem=20.5; //tarifa normal
         Double desc=(Double.parseDouble(textDescuento.getText()));
         if (opcionSiPremium.isSelected()){
           tarifa=prem-desc;
           JOptionPane.showMessageDialog(this,"La tarifa para este usuario es: "+prem+"-"+desc+"="+tarifa , "Ingresos", JOptionPane.WARNING_MESSAGE);
         }else {
           tarifa=noprem-desc;
          JOptionPane.showMessageDialog(this,"La tarifa para este usuario es: "+noprem+"-"+desc+"="+tarifa , "Ingresos", JOptionPane.WARNING_MESSAGE);
       }
        
    }//GEN-LAST:event_botoningresosActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botoningresos;
    private javax.swing.ButtonGroup buttonGroupPremium;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelPremiun;
    private javax.swing.JRadioButton opcionNoPremium;
    private javax.swing.JRadioButton opcionSiPremium;
    private javax.swing.JTextField textContraseña;
    private javax.swing.JTextField textDescuento;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables
}
